openapi: 3.0.3
info:
  title: Course Service API
  version: 1.0.0
servers:
  - url: http://localhost:8084/api/courses
paths:
  /:
    get:
      summary: List courses (tenant scoped)
      security: [ { bearerAuth: [] } ]
      parameters:
        - in: header
          name: X-Tenant-Id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    post:
      summary: Create course (PROFESSOR/ADMIN)
      security: [ { bearerAuth: [] } ]
      responses:
        '201': { description: Created }
  /{id}:
    get:
      summary: Get course
      security: [ { bearerAuth: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

