openapi: 3.0.3
info:
  title: Exam Service API
  version: 1.0.0
servers:
  - url: http://localhost:8087/api/exams
paths:
  /:
    post:
      summary: Create exam (PROFESSOR)
      security: [ { bearerAuth: [] } ]
      responses:
        '201': { description: Created }
    get:
      summary: List exams in tenant
      security: [ { bearerAuth: [] } ]
      responses:
        '200': { description: OK }
  /{id}:
    get:
      summary: Get exam with schedule guard
      security: [ { bearerAuth: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200': { description: OK }
  /submit:
    post:
      summary: Submit answers (STUDENT)
      security: [ { bearerAuth: [] } ]
      responses:
        '200': { description: Submitted }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

