openapi: 3.0.3
info:
  title: Inventory Service API
  version: 1.0.0
servers:
  - url: http://localhost:8086/api/inventory
paths:
  /reserve:
    post:
      summary: Reserve stock (Saga consumer)
      security: [ { bearerAuth: [] } ]
      responses:
        '200': { description: Reserved }
  /release:
    post:
      summary: Release stock compensation
      security: [ { bearerAuth: [] } ]
      responses:
        '200': { description: Released }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

